name: Test

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'templates/**'
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'templates/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        id: go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build
        run: make build

  test:
    name: Run tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - 0.15.0
          - 1.0.0
    steps:
      - name: Set up Go
        id: go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run tests
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
        run: make test
